services:
  app:
    build: .
    container_name: nestjs_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://bgskoro21:bagas123@nestmongo:27017/db_nestdocker?authSource=admin'
    networks:
      - nestdocker
    volumes:
      - .:/user/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo:latest
    container_name: nestmongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: bgskoro21
      MONGO_INITDB_ROOT_PASSWORD: bagas123
      MONGO_INITDB_DATABASE: db_nestdocker
    volumes:
      - 'mongo-data:/data/db'
    networks:
      - nestdocker
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - '80:80'
    networks:
      - nestdocker
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo-data:

networks:
  nestdocker:
